# POLARIS SDK - Prompts
# Prompts para interação com modelos Claude

from .scientist_prompts import (
    SCIENTIST_SYSTEM_PROMPT,
    PROBLEM_DEFINITION_PROMPT,
    METHODOLOGY_DESIGN_PROMPT,
    SAMPLING_STRATEGY_PROMPT,
    QUESTIONNAIRE_BUILDER_PROMPT,
    DATA_ANALYSIS_PROMPT,
    PROJECTIONS_PROMPT,
    RECOMMENDATIONS_PROMPT,
    REPORT_GENERATION_PROMPT,
)

from .respondent_prompts import (
    VOTER_SYSTEM_PROMPT,
    INTERVIEW_PROMPT_TEMPLATE,
    COGNITIVE_FLOW_INSTRUCTIONS,
)

from .analysis_prompts import (
    QUALITATIVE_ANALYSIS_PROMPT,
    SENTIMENT_ANALYSIS_PROMPT,
    CLUSTER_INTERPRETATION_PROMPT,
)

__all__ = [
    # Scientist
    "SCIENTIST_SYSTEM_PROMPT",
    "PROBLEM_DEFINITION_PROMPT",
    "METHODOLOGY_DESIGN_PROMPT",
    "SAMPLING_STRATEGY_PROMPT",
    "QUESTIONNAIRE_BUILDER_PROMPT",
    "DATA_ANALYSIS_PROMPT",
    "PROJECTIONS_PROMPT",
    "RECOMMENDATIONS_PROMPT",
    "REPORT_GENERATION_PROMPT",
    # Respondent
    "VOTER_SYSTEM_PROMPT",
    "INTERVIEW_PROMPT_TEMPLATE",
    "COGNITIVE_FLOW_INSTRUCTIONS",
    # Analysis
    "QUALITATIVE_ANALYSIS_PROMPT",
    "SENTIMENT_ANALYSIS_PROMPT",
    "CLUSTER_INTERPRETATION_PROMPT",
]
